### ISSUE TITLE
Create a compatibility patch for the Toggle Harvest mod

### ISSUE THREAD

**Issue by ilyvion** [ilyvion/farming-hysteresis#11]
Based on comments from: https://steamcommunity.com/sharedfiles/filedetails/?id=2431191516

> would it be possible to create a compatibility patch for the [Toggle Harvest](steam://openurl/https://steamcommunity.com/sharedfiles/filedetails/?id=1499848654) mod, given that there are plant mods that add crops that can have multiple harvests before dying and needing to be re-sown the option to automatically disable harvest would be pretty handy.
\- [[RTB] Sarianos](https://steamcommunity.com/id/Kilain)

**Comment by alexschrod** [comment]
> Probably a little obvious but have you tried asking some of the lads over at the [RimWorld Mod Market ](https://discord.gg/k6HVPKNXz8)[discord.gg] It's mostly a commission hub but there's a lot of skilled and talented folk lurking about that generally don't have a problem answering an honest question or two, at least from what I've found anyway.
> - [[RTB] Sarianos](https://steamcommunity.com/id/Kilain)

**Comment by ilyvion** [comment]
I can't figure out what exactly this was actually a request for. If someone could give me an example of a mod that adds such multi-harvest plants that would require disabling harvest, I'll look into it again.
